args:
let
  inherit (args) pkgs;
  scripts = with pkgs; [
    myScripts.ptt
    myScripts.ptt-status
    myScripts.icanhazip
    myScripts.invoke
    myScripts.runbg
    myScripts.splash
    myScripts.toolbelt
    myScripts.viconf
    myScripts.vipkg
    myScripts.fetchfromgh
    myScripts.mkshell
    myScripts.garbage-collect
    myScripts.rebuild
    myScripts.chpaper
    myScripts.chscheme
    myScripts.keyring
    myScripts.mkscreenshots
    myScripts.moveonscreen
    myScripts.s_check
    myScripts.switchmon
    myScripts.git-compose
    myScripts.playshellsound
    myScripts.color-commit
    myScripts.mntstack
  ];
in
{
  home.packages =
    with pkgs;
    [
      (rust-bin.stable.latest.default.override {
        extensions = [
          "rust-src"
          "rust-analyzer"
          "rustfmt"
          "clippy"
          "llvm-tools-preview"
        ];
      })
      nerd-fonts.envy-code-r
      nemo
      lcov
      feh
      lazygit
      gtk3
      vicut
      imagemagick
      vlc
      lolcat
      obsidian
      zsh
      zsh-syntax-highlighting
      zsh-history-substring-search
      zsh-autosuggestions
      gh
      tokei
      #libreoffice
      gtrash
      awww
      ripgrep
      toilet
      dash
      vkbasalt
      firefox
      spotify
      zathura
      tor
      tor-browser
      chromium
      obs-studio
      gparted
      dust
      porsmo
      w3m
      sox
      neovide
      claude-code
      myPython
      monero-cli
      protonup-qt
      piper
      libratbag
      whoa
      ghostty
      firefox
      fd
      delta
      glfw
      mesa-demos
      xwayland
      discord
      wine64
      gimp
      protontricks
      vesktop
      p7zip
      fira-code
      nerd-fonts.fira-code
      nodejs_latest
      myPkgs.noto-sans-jp
      myPkgs.billy-font
    ]
    ++ scripts;
}
